<a href="https://colab.research.google.com/github/Alsr96/Neural-networks/blob/master/neural_network_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow

In [0]:
import tensorflow as tf
import numpy as np

### Placeholders

* Placeholders: undefined variables, not initialised. Represents some value, holds a place for some value. Useful to define inputs and outputs of a function.
* A plceholder can be defined using datatype, shape of the value and name.

In [29]:
a = tf.placeholder(tf.float32, shape=(4,), name='placeholder_a')
b = tf.placeholder(tf.float32, shape=(4,), name='placeholder_b')
c = tf.placeholder(tf.float32, shape=(None,4), name='placeholder_c')
d = tf.placeholder(tf.float32)
e = tf.placeholder()

TypeError: ignored

* We defined a bunch of placeholders in the above code.
* Running the above code will give an error, dtype is a necessary argument, shape and name are not.
* Why is shape not necessary? We are not giving it any values, we might not know what it might be. None represents that any size can go theough it.
* Name represents the variable's name on the graph which may not be the same as the assigned variable to the value.
* They don't have values but we can use them in functions.

In [30]:
add_a_b = tf.add(a,b,name='addition')
multiply_c_d = tf.multiply(c,d, name='multiplication')
matmul_c_d = tf.matmul(c,d, name='matrix_multiplication')
matmul_b_c = tf.matmul(b,c, name='matrix_multiplication')

ValueError: ignored

* line 4 gives us an error, the dimensions must match
* add and multiply are from tf.math module which perform elementwise, they can also be accessed with tf.math.add and tf.math.multiply respectively
* matmul performs a matrix multiplication, from tf.linalg (linear algebra) module. Can be accessed as tf.linalg.matmul, it has other arguments to transpose, find adjoint etc of the inputs.
* We have defined the functions but they won't give us any values since the placeholders don't have any values.

To pass values through them we need to create a session and 'feed' the values.

In [28]:
with tf.Session() as sess:
  print('a = \n',sess.run(a, feed_dict={a:[1,2,3,4]}))
  print('d = \n',sess.run(d, feed_dict={d:[[1,2],[3,4],[5,6]]}))
  print('a+b = \n',sess.run(add_a_b, feed_dict={a:[1,2,3,4],b:[10,11,12,13]}))
  print('c.*d = \n',sess.run(multiply_c_d, feed_dict={c:[[1,2,3,4],[5,6,7,8]],d:[[11,12,13,14],[15,16,17,18]]}))
  print('c*d = \n',sess.run(matmul_c_d, feed_dict={c:[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],d:[[1],[2],[3],[4]]}))


a = 
 [1. 2. 3. 4.]
d = 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
a+b = 
 [11. 13. 15. 17.]
c.*d = 
 [[ 11.  24.  39.  56.]
 [ 75.  96. 119. 144.]]
c*d = 
 [[ 30.]
 [ 70.]
 [110.]
 [150.]]


* So we create a session using tf.Session() (note the capital 'S') and use run.
* run has 2 main arguments: the 1st one is what it fetches, the function, placeholder etc we need to run and second one feeds the input.
* Notice that we can pass any shape in 'd' . Data with shapes (3,2), (2,4) and (4,1) were passed.
* We can pass different shapes in 'c' too but it's restricted when compared to 'd'. We can only vary the 1st dimension. Data with shapes (2,4) and (4,4) were passed.